# Generated by Django 3.2.8 on 2021-12-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
