# Generated by Django 3.2.8 on 2021-12-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0004_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='buatproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('judul', models.CharField(max_length=50)),
                ('type_user', models.CharField(max_length=50)),
                ('jenis_jasa', models.CharField(max_length=50)),
                ('alamat_jasa', models.CharField(max_length=50)),
                ('price_jasa', models.IntegerField()),
                ('deadline_jasa', models.CharField(max_length=50)),
                ('catatan', models.TextField(max_length=1000)),
            ],
        ),
    ]
